DolevSeri/EKrut_final

EkrutClient/src/clientControllers/AreaManager_MainViewController.java
=> test commit

EkrutClient/src/clientControllers/ConnectFormController.java, EkrutClient/src/clientGUI/Identification_Interface.fxml
=> updated screen load

EkrutClient/bin/.gitignore, EkrutClient/src/client/ChatClient.java, EkrutClient/src/clientControllers/IdentificationController.java, EkrutClient/src/entityControllers/UserController.java, EkrutCommon/src/entities/User.java, EkrutCommon/src/enums/Region.java, EkrutCommon/src/enums/Role.java, EkrutServer/src/server/EchoServer.java, EkrutServer/src/server/MySqlController.java
=> Login-Final result!

EkrutClient/bin/clientGUI/Identification_Interface.fxml, EkrutClient/src/clientControllers/IdentificationController.java, EkrutClient/src/clientGUI/Identification_Interface.fxml, EkrutServer/src/server/MySqlController.java
=> workingon indentification and mysql

EkrutClient/.classpath, EkrutClient/bin/clientGUI/Client_OL_MainView.fxml, EkrutClient/bin/clientGUI/ConnectForm.fxml, EkrutClient/bin/clientGUI/Identification_Interface.fxml, EkrutClient/src/client/ChatClient.java, EkrutClient/src/clientControllers/Client_OL_MainVieController.java, EkrutClient/src/clientControllers/ConnectFormController.java, EkrutClient/src/clientControllers/IdentificationController.java, EkrutClient/src/clientControllers/MainOrderFrameController.java, EkrutClient/src/clientControllers/SetSceneController.java, EkrutClient/src/clientGUI/Client_OL_MainView.fxml, EkrutClient/src/clientGUI/ConnectForm.fxml, EkrutClient/src/clientGUI/Identification_Interface.fxml, EkrutClient/src/clientGUI/MainOrderFrame.fxml, EkrutCommon/.classpath, EkrutCommon/src/enums/Request.java, EkrutServer/.classpath, EkrutServer/src/server/EchoServer.java, EkrutServer/src/server/MySqlController.java, OCSF/.classpath
FUNCTUINALITY !!!!
teasher ya maniak
=> We fixed logout and exit button, and WE DONE LOGIN AND LOGOUT

EkrutClient/bin/clientGUI/Client_EK_MainView.fxml, EkrutClient/bin/clientGUI/Client_OrderScreen.fxml, EkrutClient/src/clientControllers/Client_EK_MainViewController.java, EkrutClient/src/clientControllers/Client_OrderScreenController.java, EkrutClient/src/clientControllers/MainOrderFrameController.java, EkrutClient/src/clientGUI/Client_EK_MainView.fxml, EkrutClient/src/clientGUI/Client_OrderScreen.fxml
setted some screens to work untill order screen
=> setted some screens to work untill order screen

EkrutClient/src/client/ChatClient.java, EkrutClient/src/clientControllers/Client_EK_MainViewController.java, EkrutClient/src/clientControllers/Client_OrderScreenController.java, EkrutClient/src/clientControllers/IdentificationController.java, EkrutClient/src/clientControllers/ProductController.java, EkrutClient/src/entityControllers/CostumerController.java, EkrutCommon/src/entities/Costumer.java, EkrutCommon/src/entities/Product.java, EkrutCommon/src/entities/ProductInDevice.java, EkrutCommon/src/enums/CostumerStatus.java, EkrutCommon/src/enums/Devices.java, EkrutCommon/src/enums/Request.java, EkrutServer/src/server/EchoServer.java, EkrutServer/src/server/MySqlController.java
=> continue in order proccess

EkrutClient/bin/clientGUI/Client_OrderScreen.fxml, EkrutClient/src/clientControllers/Client_OrderScreenController.java, EkrutClient/src/clientControllers/IdentificationController.java, EkrutClient/src/clientControllers/ProductController.java, EkrutClient/src/clientGUI/Client_OrderScreen.fxml, EkrutClient/src/clientGUI/Product.fxml, EkrutCommon/src/entities/Costumer.java, EkrutCommon/src/entities/ProductInDevice.java, EkrutCommon/src/enums/Devices.java, EkrutCommon/src/enums/ProductStatus.java, EkrutCommon/src/enums/Region.java, EkrutServer/src/server/MySqlController.java
=> screen order updated !

EkrutClient/src/clientControllers/Client_OrderScreenController.java, EkrutCommon/src/entities/Costumer.java, EkrutCommon/src/entities/ProductInDevice.java, EkrutServer/src/server/MySqlController.java
=> new changes of devices

EkrutClient/bin/clientGUI/Client_OrderScreen.fxml, EkrutClient/src/clientControllers/Client_OrderScreenController.java, EkrutClient/src/clientControllers/ProductController.java, EkrutClient/src/clientControllers/ProductInCartController.java, EkrutClient/src/clientGUI/Client_OrderScreen.fxml, EkrutClient/src/clientGUI/Product.fxml, EkrutClient/src/clientGUI/ProductInCart.fxml
=> order cart and catalog working..

EkrutClient/src/clientControllers/IdentificationController.java, EkrutClient/src/clientGUI/ScreenForNotApproveUserAfterLogin.fxml, EkrutClient/src/clientGUI/ScreenForNotSignUpUser.fxml
=> Login Screen

EkrutClient/bin/clientGUI/Client_EK_MainView.fxml, EkrutClient/bin/clientGUI/Client_OL_MainView.fxml, EkrutClient/bin/clientGUI/Client_OrderConfirmation.fxml, EkrutClient/bin/clientGUI/Client_OrderScreen.fxml, EkrutClient/bin/clientGUI/Identification_Interface.fxml, EkrutClient/src/clientControllers/Client_OL_MainVieController.java, EkrutClient/src/clientControllers/Client_OrderConfirmationController.java, EkrutClient/src/clientControllers/Client_OrderScreenController.java, EkrutClient/src/clientControllers/IdentificationController.java, EkrutClient/src/clientControllers/ProductController.java, EkrutClient/src/clientControllers/ProductInCartController.java, EkrutClient/src/clientGUI/Client_EK_MainView.fxml, EkrutClient/src/clientGUI/Client_OL_MainView.fxml, EkrutClient/src/clientGUI/Client_OrderConfirmation.fxml, EkrutClient/src/clientGUI/Client_OrderScreen.fxml, EkrutClient/src/clientGUI/Identification_Interface.fxml, EkrutClient/src/clientGUI/Product.fxml
fixed button Cancel and screen of order
=> fixed button Cancel in order screen.

EkrutClient/src/clientControllers/IdentificationController.java, EkrutClient/src/clientGUI/ScreenForNotApproveUserAfterLogin.fxml, EkrutClient/src/clientGUI/ScreenForNotSignUpUser.fxml
=> LogInUserNotApprove

EkrutCommon/src/entities/CostumersReport.java, EkrutCommon/src/entities/InventoryReport.java, EkrutServer/src/server/MySqlController.java
Added Inventory and Costumers report classes.
Added function of get Inventory report from DB.
not done but whatever :)
=> Inventory and costumers report classes.

EkrutClient/src/client/ChatClient.java, EkrutClient/src/clientControllers/AreaManager_CostumerApprovalController.java, EkrutClient/src/clientControllers/AreaManager_MainViewController.java, EkrutClient/src/clientControllers/AreaManager_SetTresholdController.java, EkrutClient/src/clientControllers/TableViewController.java, EkrutClient/src/clientGUI/AreaManager_CostumerApproval.fxml, EkrutClient/src/entityControllers/CostumerController.java, EkrutClient/src/entityControllers/DeviceController.java, EkrutCommon/src/entities/Costumer.java, EkrutCommon/src/entities/User.java, EkrutCommon/src/enums/Request.java, EkrutServer/src/server/EchoServer.java, EkrutServer/src/server/MySqlController.java
=> Customers approval done

EkrutClient/src/client/ChatClient.java, EkrutClient/src/clientControllers/Client_OrderScreenController.java, EkrutClient/src/clientControllers/ProductController.java, EkrutClient/src/clientControllers/ProductInCartController.java, EkrutClient/src/entityControllers/CartController.java
almost finished with regular order, covered the all screen problems
=> almost finished with regular order, covered the all screen problems

EkrutClient/bin/clientGUI/Client_OrderConfirmation.fxml, EkrutClient/src/clientControllers/Client_OrderConfirmationController.java, EkrutClient/src/clientControllers/ProductInConfirmationController.java, EkrutClient/src/clientGUI/Client_OrderConfirmation.fxml, EkrutClient/src/clientGUI/ProductInConfirmation.fxml, EkrutClient/src/entityControllers/CartController.java, EkrutCommon/src/entities/MessageInSystem.java, EkrutCommon/src/enums/Request.java
=> Order LAST DETAILS

EkrutClient/src/clientGUI/UserManagement_MainView.fxml.fxml
=> EdenForYou

EkrutClient/bin/clientGUI/Client_OrderCanceled.fxml, EkrutClient/bin/clientGUI/Client_OrderCompleteMsg.fxml, EkrutClient/bin/clientGUI/SalesManager_CreateSale.fxml, EkrutClient/bin/clientGUI/SalesWorker_ActivateSale.fxml, EkrutClient/bin/clientGUI/SalesWorker_CreatePattern.fxml, EkrutClient/bin/clientGUI/SalesWorker_MainView.fxml, EkrutClient/src/client/ChatClient.java, EkrutClient/src/clientControllers/Client_OrderCanceledController.java, EkrutClient/src/clientControllers/Client_OrderCompleteMsgController.java, EkrutClient/src/clientControllers/Client_OrderConfirmationController.java, EkrutClient/src/clientControllers/Client_OrderScreenController.java, EkrutClient/src/clientControllers/ConnectFormController.java, EkrutClient/src/clientControllers/ProductInCartController.java, EkrutClient/src/clientControllers/ProductInConfirmationController.java, EkrutClient/src/clientGUI/Client_OrderCanceled.fxml, EkrutClient/src/clientGUI/Client_OrderCompleteMsg.fxml, EkrutClient/src/clientGUI/ProductInConfirmation.fxml, EkrutClient/src/entityControllers/MessageInSystemController.java, EkrutClient/src/entityControllers/OrderController.java, EkrutCommon/src/entities/MessageInSystem.java, EkrutCommon/src/enums/Request.java, EkrutCommon/src/enums/SupplyMethod.java, EkrutServer/src/server/EchoServer.java, EkrutServer/src/server/MySqlController.java
=> regular order DONE

EkrutClient/bin/clientGUI/SalesManager_CreateSale.fxml, EkrutClient/bin/clientGUI/SalesWorker_CreatePattern.fxml, EkrutClient/src/client/ChatClient.java, EkrutClient/src/clientControllers/PopUpMessageController.java, EkrutClient/src/clientControllers/SalesManagerCreateSaleController.java, EkrutClient/src/clientControllers/SalesManagerMainScreenController.java, EkrutClient/src/clientControllers/SalesWorkerCreatePatternController.java, EkrutClient/src/clientGUI/PopUpMessage.fxml, EkrutClient/src/clientGUI/SalesManagerMainScreen.fxml, EkrutClient/src/clientGUI/SalesManager_CreateSale.fxml, EkrutClient/src/clientGUI/SalesWorker_CreatePattern.fxml, EkrutClient/src/entityControllers/SaleController.java, EkrutClient/src/entityControllers/SalesPatternController.java, EkrutCommon/src/entities/Sale.java, EkrutCommon/src/enums/Request.java, EkrutCommon/src/enums/SaleStatus.java, EkrutServer/src/server/EchoServer.java, EkrutServer/src/server/MySqlController.java
=> SalesUpdate(:

EkrutClient/src/clientControllers/AreaManager_InventoryCallsController.java, EkrutCommon/src/common/ClientConnected.java, EkrutServer/src/server/EchoServer.java, EkrutServer/src/server/MySqlController.java
=> Inventory Calls Manager side

EkrutClient/src/clientControllers/Client_OrderConfirmationController.java
another commit for update system messages
=> another commit

EkrutServer/src/server/EchoServer.java, EkrutServer/src/server/MySqlController.java
=> fixed bugs

EkrutClient/bin/clientGUI/InventoryOperationWorker_CallsListView.fxml, EkrutClient/bin/clientGUI/InventoryOperationWorker_MainView.fxml, EkrutClient/src/clientControllers/InventoryOperationWorker_InventoryCallsController.java, EkrutClient/src/clientControllers/InventoryOperationWorker_MainViewController.java, EkrutClient/src/clientGUI/InventoryOperationWorker_CallsListView.fxml, EkrutClient/src/clientGUI/InventoryOperationWorker_MainView.fxml, EkrutCommon/src/enums/CallStatus.java, EkrutCommon/src/enums/Role.java
started to work on operation worker
=> started to work on operation worker

EkrutClient/src/client/ChatClient.java, EkrutClient/src/clientControllers/ChooseDevice_PickUpController.java, EkrutClient/src/clientControllers/Client_DeliveryConfirmationController.java, EkrutClient/src/clientControllers/Client_EK_MainViewController.java, EkrutClient/src/clientControllers/Client_OL_MainVieController.java, EkrutClient/src/clientControllers/Client_OrderConfirmationController.java, EkrutClient/src/clientControllers/Client_OrderScreenController.java, EkrutClient/src/clientControllers/SetSceneController.java, EkrutClient/src/entityControllers/InactivityLogoutController.java
thread 15 minitues for order  works
=> thread for order works

EkrutClient/bin/clientGUI/Client_EK_MainView.fxml, EkrutClient/src/clientControllers/Client_DeliveryConfirmationController.java, EkrutClient/src/clientControllers/Client_EK_MainViewController.java, EkrutClient/src/clientControllers/Client_OL_MainVieController.java, EkrutClient/src/clientControllers/Client_OrderConfirmationController.java, EkrutClient/src/clientGUI/Client_EK_MainView.fxml
=> some doucments

EkrutClient/src/client/ChatClient.java, EkrutClient/src/clientControllers/Client_OrderConfirmationController.java, EkrutClient/src/clientControllers/InventoryOperationWorker_UpdateProductQuantityController.java, EkrutClient/src/entityControllers/UserController.java, EkrutCommon/src/enums/Request.java, EkrutServer/src/server/EchoServer.java, EkrutServer/src/server/MySqlController.java
=> fix inbar bugs

EkrutServer/src/serverControllers/EndOfMonthChecker.java, EkrutServer/src/serverControllers/ServerPortFrameController.java
=> Reports Thread

EkrutClient/src/client/ChatClient.java, EkrutClient/src/client/ChatClientIF.java, EkrutClient/src/client/ScreenInterface.java, EkrutClient/src/clientControllers/IdentificationController.java, EkrutServer/src/server/EchoServer.java, EkrutServer/src/server/ServerUI.java
=> ADDING A SINGLETON TO SERVER AND START DEPENDENCY INJECTION FOR LOGIN

EkrutClient/src/clientControllers/Client_OrderConfirmationController.java, EkrutClient/src/clientControllers/ProductController.java, EkrutClient/src/clientControllers/ProductInCartController.java
=> bug fixed order

EkrutClient/src/client/ChatClient.java, EkrutClient/src/clientControllers/AreaManager_CostumerApprovalController.java, EkrutClient/src/clientControllers/DeliveryOperator_ManageDeliveriesController.java, EkrutClient/src/clientControllers/InventoryOperationWorker_UpdateProductQuantityController.java, EkrutClient/src/clientGUI/DeliveryOperator_ManageDeliveries.fxml, EkrutClient/src/entityControllers/DeliveryController.java, EkrutCommon/src/enums/Request.java, EkrutServer/src/server/EchoServer.java, EkrutServer/src/server/MySqlController.java
=> all messages that need to be sent are working + documentation for

EkrutCommon/src/entities/Costumer.java, EkrutCommon/src/entities/CostumersReport.java, EkrutCommon/src/entities/Delivery.java, EkrutCommon/src/entities/DeliveryReport.java, EkrutCommon/src/entities/Device.java, EkrutCommon/src/entities/InventoryCall.java, EkrutCommon/src/entities/InventoryReport.java, EkrutCommon/src/entities/Message.java, EkrutCommon/src/entities/Order.java, EkrutCommon/src/entities/OrderReport.java, EkrutCommon/src/entities/Product.java, EkrutCommon/src/entities/ProductInDevice.java, EkrutCommon/src/entities/Sale.java, EkrutCommon/src/entities/SalesPattern.java, EkrutCommon/src/entities/Subscriber.java, EkrutCommon/src/entities/User.java
document all entities in common project.
=> document all entities in common project.

EkrutClient/src/client/ChatClient.java, EkrutClient/src/clientControllers/Client_OrderConfirmationController.java, EkrutCommon/src/entities/ProductUnderThreshold.java, EkrutCommon/src/enums/Request.java, EkrutServer/src/server/EchoServer.java, EkrutServer/src/server/MySqlController.java
added product to table when its under threshold level
=> added product to table when its under threshold level

EkrutServer/src/server/MySqlController.java, EkrutServer/src/serverControllers/EndOfMonthChecker.java, EkrutServer/src/serverControllers/ServerPortFrameController.java
Fixed bugs with thread and reports
=> Fixed bugs with thread and reports

EkrutServer/src/server/MySqlController.java, EkrutServer/src/serverControllers/EndOfMonthChecker.java, EkrutServer/src/serverControllers/ServerPortFrameController.java
=> Import works

EkrutClient/bin/clientGUI/CEO_MainView.fxml, EkrutClient/bin/clientGUI/MonthllyInventoryReport.fxml, EkrutClient/src/clientControllers/CEO_MainViewController.java, EkrutClient/src/clientControllers/ChooseReportController.java, EkrutClient/src/clientControllers/InventoryReportController.java, EkrutClient/src/clientGUI/CEO_MainView.fxml, EkrutClient/src/clientGUI/MonthllyInventoryReport.fxml, EkrutClient/src/entityControllers/InventoryReportController.java, EkrutServer/src/server/MySqlController.java
=> fixed bugs cosomo

EkrutClient/bin/clientGUI/AreaManager_InventoryCalls.fxml, EkrutClient/bin/clientGUI/AreaManager_InventoryManagementForm.fxml, EkrutClient/bin/clientGUI/AreaManager_TresholdSet.fxml, EkrutClient/bin/clientGUI/Client_DeliveryConfirmation.fxml, EkrutClient/bin/clientGUI/Client_EK_MainView.fxml, EkrutClient/bin/clientGUI/Client_OL_MainView.fxml, EkrutClient/bin/clientGUI/MonthllyInventoryReport.fxml, EkrutClient/bin/clientGUI/SalesWorker_MainView.fxml, EkrutClient/src/clientControllers/Client_EK_MainViewController.java, EkrutClient/src/clientControllers/Client_OL_MainVieController.java, EkrutClient/src/clientControllers/DeliveryReportController.java, EkrutClient/src/clientControllers/InventoryReportController.java, EkrutClient/src/clientControllers/UserManagement_UserInformationController.java, EkrutClient/src/clientGUI/AreaManager_CostumerApproval.fxml, EkrutClient/src/clientGUI/AreaManager_InventoryCalls.fxml, EkrutClient/src/clientGUI/AreaManager_InventoryManagementForm.fxml, EkrutClient/src/clientGUI/AreaManager_TresholdSet.fxml, EkrutClient/src/clientGUI/ChooseReport.fxml, EkrutClient/src/clientGUI/Client_DeliveryConfirmation.fxml, EkrutClient/src/clientGUI/Client_EK_MainView.fxml, EkrutClient/src/clientGUI/Client_OL_MainView.fxml, EkrutClient/src/clientGUI/MonthllyInventoryReport.fxml, EkrutClient/src/clientGUI/MonthlyDeliveryReport.fxml, EkrutClient/src/clientGUI/SalesWorker_MainView.fxml, EkrutClient/src/clientGUI/ScreenForNotApproveUserAfterLogin.fxml, EkrutClient/src/clientGUI/ScreenForNotSignUpUser.fxml, EkrutClient/src/clientGUI/UsersManagement_UsersDataView.fxml, EkrutServer/src/server/MySqlController.java, EkrutServer/src/serverControllers/ServerPortFrameController.java
=> final commit !!!!

EkrutClient/bin/clientGUI/Client_ApproveGettingDelivery.fxml, EkrutClient/src/client/ChatClient.java, EkrutClient/src/clientControllers/AreaManager_CostumerApprovalController.java, EkrutClient/src/clientControllers/SaleCoulmnController.java, EkrutClient/src/clientControllers/SalesManagerCreateSaleController.java, EkrutClient/src/clientControllers/SalesWorkerActivateSaleController.java, EkrutClient/src/clientGUI/Client_ApproveGettingDelivery.fxml, EkrutClient/src/entityControllers/InactivityLogoutController.java, EkrutClient/src/entityControllers/SaleController.java, EkrutCommon/src/enums/Request.java, EkrutServer/src/server/EchoServer.java, EkrutServer/src/server/MySqlController.java
=> FINAL COSOMO

EkrutClient/UnitTestClient/clientControllers/IdentificationControllerTest.java, EkrutClient/src/clientControllers/IdentificationController.java, EkrutCommon/src/entities/User.java, EkrutServer/src/server/EchoServer.java, EkrutServer/src/server/MySqlController.java, EkrutServer/unitTest/MySqlControllerTest.java
testing for loggin in server side
=> testing for loggin in server side

EkrutClient/src/client/ClientUI.java
=> commendLine

EkrutClient/UnitTestClient/clientControllers/IdentificationControllerTest.java, EkrutClient/src/client/ClientUI.java, EkrutClient/src/clientControllers/IdentificationController.java
=> tests commit

EkrutClient/UnitTestClient/clientControllers/IdentificationControllerTest.java, EkrutClient/src/client/ClientUI.java, EkrutClient/src/clientControllers/IdentificationController.java
=> Test login client

EkrutClient/UnitTestClient/clientControllers/IdentificationControllerTest.java, EkrutClient/src/clientControllers/IdentificationController.java, EkrutClient/src/entityControllers/UserController.java, EkrutCommon/src/entities/User.java, EkrutCommon/src/enums/Role.java, EkrutServer/src/server/EchoServer.java
=> test continue

EkrutClient/UnitTestClient/clientControllers/IdentificationControllerTest.java, EkrutClient/src/clientControllers/IdentificationController.java, EkrutServer/src/server/MySqlController.java, EkrutServer/unitTest/MySqlControllerTest.java
=> testsssssss

EkrutClient/UnitTestClient/clientControllers/IdentificationControllerTest.java, EkrutClient/src/clientControllers/IdentificationController.java, EkrutServer/src/server/MySqlController.java, EkrutServer/unitTest/MySqlControllerTest.java
=> Last committed

EkrutServer/unitTest/MySqlControllerTest.java
=> TestDoneToLogin
